services:
  - name: jitsi-web
    type: web
    env: docker
    dockerfilePath: web/Dockerfile
    plan: standard
    autoDeploy: true
    envVars:
      - fromGroup: jitsi-common

  - name: jitsi-prosody
    type: web
    env: docker
    dockerfilePath: prosody/Dockerfile
    plan: standard
    autoDeploy: true
    envVars:
      - fromGroup: jitsi-common

  - name: jitsi-jicofo
    type: web
    env: docker
    dockerfilePath: jicofo/Dockerfile
    plan: standard
    autoDeploy: true
    envVars:
      - fromGroup: jitsi-common

  - name: jitsi-jvb
    type: web
    env: docker
    dockerfilePath: jvb/Dockerfile
    plan: standard
    autoDeploy: true
    envVars:
      - fromGroup: jitsi-common

envVarGroups:
  - name: jitsi-common
    envVars:
      - key: JITSI_IMAGE_VERSION
        value: unstable
      - key: PUBLIC_URL
        value: https://meet.example.com
      - key: XMPP_DOMAIN
        value: meet.example.com
      - key: XMPP_SERVER
        value: jitsi-prosody
      - key: JICOFO_AUTH_USER
        value: focus
      - key: ENABLE_LETSENCRYPT
        value: "1"
      - key: ENABLE_HTTP_REDIRECT
        value: "1"
      - key: ENABLE_XMPP_WEBSOCKET
        value: "1"
